<?php

namespace Database\Seeders;

use App\Models\FeatureFlag;
use Illuminate\Database\Seeder;

class FeatureFlagsSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $flags = [
            'enable_cms',
            'enable_media_library',
            'enable_theme_foundation',
            'enable_package_foundation',
            'enable_rabet_foundation',
            'enable_onboarding_basic',
            'enable_activity_logs',
            'enable_cms_menus',
            'enable_cms_redirects',
            'enable_seo_tools',
            'enable_forms',
            'enable_lead_capture',
            'enable_wordpress_import',
            'enable_theme_catalog',
            'enable_theme_app_recipes',
            'enable_package_catalog',
            'enable_plugin_bundles',
            'enable_commerce_lite',
            'enable_external_source_registry',
            'enable_crm_operations',
            'enable_service_requests',
            'enable_quotations',
            'enable_invoicing',
            'enable_manual_payments',
            'enable_inventory_lite',
            'enable_purchasing',
            'enable_accounting_starter',
            'enable_people_operations',
            'enable_projects_tasks',
            'enable_workflow_basic',
            'enable_reports_basic',
            'enable_dashboard_widgets',
            'enable_organization_operating_modes',
            'enable_cloud_sites',
            'enable_cloud_domains',
            'enable_cloud_backups',
            'enable_cloud_health_checks',
            'enable_mall_publication_consents',
            'enable_mall_sync_sources',
            'enable_mall_mirrors',
            'enable_mall_public_browsing',
            'enable_public_feed_sync',
            'enable_backoffice_anywhere',
            'enable_moderation_cases',
            'enable_reviews_ratings',
            'enable_reputation_trust',
            'enable_legal_partner_network',
            'enable_internal_marketplace',
            'enable_creator_profiles',
            'enable_agency_partners',
            'enable_work_network',
            'enable_academy_badges',
            'enable_growth_referrals',
            'enable_partner_storefronts',
            'enable_erp_pro_foundation',
            'enable_sales_pro_documents',
            'enable_invoice_links',
            'enable_inventory_pro',
            'enable_purchasing_pro',
            'enable_accounting_posting',
            'enable_clm_basic',
            'enable_helpdesk_basic',
            'enable_pos_basic',
            'enable_commission_engine',
            'enable_partner_payouts',
            'enable_advanced_erp_approvals',
            'enable_integration_hub',
            'enable_integration_oauth_placeholders',
            'enable_integration_mapping_engine',
            'enable_integration_retry_conflicts',
            'enable_integration_webhooks',
            'enable_integration_rate_limits',
            'enable_external_catalog_sync_advanced',
            'enable_advanced_reporting_v5',
            'enable_package_operations_v5',
            'enable_package_signing_reviews',
            'enable_billing_usage_records',
            'enable_enterprise_security_v6',
            'enable_siem_exports',
            'enable_public_developer_marketplace',
            'enable_universal_connector_sdk',
            'enable_universal_sync_advanced',
            'enable_mall_advanced_v6',
            'enable_data_platform_v6',
            'enable_grc_v6',
            'enable_enterprise_architecture_v6',
            'enable_industry_solutions_v6',
            'enable_ai_cobuilder_v6',
            'enable_marketplace_revenue_share_v6',
            'enable_enterprise_api_gateway',
            'enable_data_privacy_retention_v6',
            'enable_performance_scale_v6',
            'enable_mobile_app_config',
            'enable_mobile_theme_profiles',
            'enable_mobile_api_manifest',
            'enable_mobile_device_registry',
            'enable_mobile_push_tokens',
            'enable_mobile_public_apis',
            'enable_mobile_auth_apis',
            'enable_desktop_client_registry',
            'enable_desktop_sync_sessions',
            'enable_desktop_pull_api',
            'enable_desktop_push_dry_run',
            'enable_desktop_outbox_operations',
            'enable_desktop_conflict_detection',
            'enable_desktop_file_queue',
        ];

        foreach ($flags as $key) {
            FeatureFlag::query()->updateOrCreate(
                ['key' => $key],
                [
                    'description' => null,
                    'default_value' => false,
                    'status' => 'active',
                ],
            );
        }
    }
}
