<?php

return [
    'version' => 'V15',
    'name' => 'KABEERI Next.js Public Runtime Scaffold and API Contract',
    'rules' => [
        'runtime_boundary' => 'Next.js owns public theme rendering; Laravel owns domain logic, data, policies, jobs, and JSON contracts.',
        'blade_bridge' => 'Blade remains a temporary bridge for current public pages until route parity and API contracts are production-ready.',
        'api_only' => 'The public runtime must consume documented JSON endpoints and must not depend on Laravel models, Blade partials, or database access.',
        'rtl_first' => 'Arabic RTL is first-class. Locale, direction, logical spacing, semantic HTML, and accessible focus states are required.',
        'marketplace_mall_separation' => 'Kabeeri Marketplace is the extension economy. Kabeeri Mall is public discovery and lead flow.',
    ],
    'workspace' => [
        'path' => 'apps/public-web',
        'package' => '@kabeeri/public-web',
        'framework' => 'Next.js App Router',
        'language' => 'TypeScript',
        'styling' => 'Tailwind CSS 4 plus Kabeeri design tokens',
        'scripts' => [
            'build' => 'next build',
            'typecheck' => 'tsc --noEmit',
            'test:smoke' => 'node tests/smoke/public-runtime-contract.test.mjs',
        ],
    ],
    'api' => [
        'manifest_route' => 'public-web.manifest',
        'manifest_uri' => '/api/public-web/manifest',
        'contract_version' => 'public-web.v1',
        'visibility' => 'public scaffold metadata only; no tenant-private data',
        'endpoints' => [
            'manifest' => '/api/public-web/manifest',
            'pricing' => '/pricing',
            'audiences' => '/for',
            'marketplace' => '/marketplace',
            'mall' => '/mall',
        ],
    ],
    'routes' => [
        ['key' => 'home', 'path' => '/ar', 'title' => 'Kabeeri Public Runtime Home', 'source' => 'V11 public narrative'],
        ['key' => 'audiences', 'path' => '/ar/for', 'title' => 'Audience Paths', 'source' => 'V11 audience selector'],
        ['key' => 'pricing', 'path' => '/ar/pricing', 'title' => 'Pricing and Subscriptions', 'source' => 'V11 pricing'],
        ['key' => 'marketplace', 'path' => '/ar/marketplace', 'title' => 'Kabeeri Marketplace', 'source' => 'V12 marketplace/developer UX'],
        ['key' => 'developers', 'path' => '/ar/developers', 'title' => 'Developer Economy', 'source' => 'V12 developer portal'],
        ['key' => 'mall', 'path' => '/ar/mall', 'title' => 'Kabeeri Mall', 'source' => 'V13 external Mall UX'],
    ],
    'audience_paths' => [
        ['key' => 'business', 'label' => 'Business owners', 'promise' => 'Launch a Kabeeri App, then grow into commerce, CRM, operations, and Mall visibility.', 'route' => '/ar/for'],
        ['key' => 'enterprise', 'label' => 'Enterprise buyers', 'promise' => 'Govern teams, permissions, integrations, auditability, BI, and GRC adoption.', 'route' => '/ar/for'],
        ['key' => 'developers', 'label' => 'Developers and creators', 'promise' => 'Build themes, plugins, connectors, and business kits for the platform economy.', 'route' => '/ar/developers'],
        ['key' => 'partners', 'label' => 'Marketers and partners', 'promise' => 'Run campaigns, referrals, storefronts, lead handoff, and measurable growth paths.', 'route' => '/ar/for'],
    ],
    'theme_manifest' => [
        'id' => 'kabeeri-public-foundation',
        'version' => '0.1.0',
        'runtime' => 'next-app-router',
        'locales' => ['ar', 'en'],
        'default_locale' => 'ar',
        'default_direction' => 'rtl',
        'components' => ['Hero', 'AudienceGrid', 'OnboardingTimeline', 'MarketplaceMallSplit', 'DeveloperEconomy', 'RuntimeBoundary', 'OwnerConsole'],
        'api_contracts' => ['public-web.v1'],
        'quality' => ['rtl', 'responsive', 'accessible', 'api-only', 'marketplace-mall-separated'],
    ],
    'quality_gates' => [
        ['key' => 'v14_ready', 'label' => 'V14 UI release candidate remains ready'],
        ['key' => 'manifest_route_ready', 'label' => 'Laravel public-web manifest endpoint exists'],
        ['key' => 'workspace_ready', 'label' => 'apps/public-web workspace exists'],
        ['key' => 'next_files_ready', 'label' => 'Next.js App Router, components, API client, theme manifest, tokens, and smoke tests exist'],
        ['key' => 'package_scripts_ready', 'label' => 'Root and workspace package scripts are registered'],
        ['key' => 'docs_ready', 'label' => 'V15 docs and handoff exist'],
        ['key' => 'tracker_synced', 'label' => 'V15 task tracker matches implementation truth'],
    ],
    'required_files' => [
        'apps/public-web/package.json',
        'apps/public-web/next.config.ts',
        'apps/public-web/tsconfig.json',
        'apps/public-web/app/layout.tsx',
        'apps/public-web/app/[locale]/page.tsx',
        'apps/public-web/app/globals.css',
        'apps/public-web/styles/tokens.css',
        'apps/public-web/components/ui/ActionLink.tsx',
        'apps/public-web/components/ui/SurfaceCard.tsx',
        'apps/public-web/components/sections/PublicRuntimePage.tsx',
        'apps/public-web/lib/api/publicRuntime.ts',
        'apps/public-web/lib/navigation/routes.ts',
        'apps/public-web/lib/theme-manifest/kabeeriPublicFoundation.ts',
        'apps/public-web/tests/smoke/public-runtime-contract.test.mjs',
    ],
];
