<?php

return [
    'version' => 'V12',
    'name' => 'KABEERI Themes, Plugins, Marketplace, and Developer Portal UX',
    'rules' => [
        'runtime' => 'Laravel Blade is a V12 bridge only. Commercial theme runtime remains Next.js + React + TypeScript + Tailwind.',
        'marketplace_vs_mall' => 'Kabeeri Marketplace sells and governs extensions. Kabeeri Mall is public discovery for businesses, products, services, talent, and travel.',
        'safe_install' => 'No package install or update can be represented without permissions, compatibility, signing, license, backup, rollback, and audit expectations.',
        'developer_first' => 'Developer and creator workflows must show package status, next required action, review feedback, revenue model, and support obligations.',
        'manifest_first' => 'Themes, plugins, and connectors are described through manifests before they are treated as UI cards.',
    ],
    'pages' => [
        'marketplace_home' => ['label' => 'Marketplace Home', 'route' => 'marketplace.home', 'uri' => '/marketplace', 'task_ids' => ['T07'], 'intent' => 'Explain Kabeeri Marketplace as the internal extension store.'],
        'theme_catalog' => ['label' => 'Theme Catalog', 'route' => 'marketplace.themes.index', 'uri' => '/marketplace/themes', 'task_ids' => ['T02', 'T23'], 'intent' => 'Browse Design Market themes with taxonomy and filters.'],
        'theme_detail' => ['label' => 'Theme Detail and Preview', 'route' => 'marketplace.themes.show', 'uri' => '/marketplace/themes/{theme}', 'task_ids' => ['T03', 'T21'], 'intent' => 'Preview theme compatibility, component runtime mapping, QA, and license.'],
        'theme_recipes' => ['label' => 'Theme Recipes', 'route' => 'marketplace.theme-recipes', 'uri' => '/marketplace/theme-recipes', 'task_ids' => ['T04'], 'intent' => 'Explain apply preview recipes by business type.'],
        'plugin_catalog' => ['label' => 'Plugin Bundle Catalog', 'route' => 'marketplace.plugins.index', 'uri' => '/marketplace/plugins', 'task_ids' => ['T05'], 'intent' => 'Browse plugin bundles by project type and risk level.'],
        'plugin_detail' => ['label' => 'Plugin Detail and Compatibility', 'route' => 'marketplace.plugins.show', 'uri' => '/marketplace/plugins/{package}', 'task_ids' => ['T06', 'T27'], 'intent' => 'Explain permissions, compatibility, dependencies, signing, and support.'],
        'licensing' => ['label' => 'Licensing and Revenue Share', 'route' => 'marketplace.licensing', 'uri' => '/marketplace/licensing', 'task_ids' => ['T22', 'T30'], 'intent' => 'Explain package pricing, licensing, commissions, payouts, and support duties.'],
        'governance' => ['label' => 'Marketplace Governance', 'route' => 'marketplace.governance', 'uri' => '/marketplace/governance', 'task_ids' => ['T16'], 'intent' => 'Show review, approval, suspension, security, and admin handoff.'],
        'review_status' => ['label' => 'Package Lifecycle Review Status', 'route' => 'marketplace.review-status', 'uri' => '/marketplace/review-status', 'task_ids' => ['T26'], 'intent' => 'Explain lifecycle statuses and next actions.'],
        'developer_landing' => ['label' => 'Developer Portal', 'route' => 'developers.portal', 'uri' => '/developers', 'task_ids' => ['T08'], 'intent' => 'Introduce the developer economy and publisher path.'],
        'developer_onboarding' => ['label' => 'Developer Onboarding', 'route' => 'developers.onboarding', 'uri' => '/developers/onboarding', 'task_ids' => ['T09', 'T24'], 'intent' => 'Convert creator/developer interest into a publisher account.'],
        'theme_builder_docs' => ['label' => 'Theme Builder Documentation', 'route' => 'developers.docs.themes', 'uri' => '/developers/docs/themes', 'task_ids' => ['T10', 'T20', 'T21'], 'intent' => 'Document component library, theme manifest, and React runtime mapping.'],
        'plugin_manifest_docs' => ['label' => 'Plugin Manifest Documentation', 'route' => 'developers.docs.plugin-manifest', 'uri' => '/developers/docs/plugin-manifest', 'task_ids' => ['T11', 'T27'], 'intent' => 'Document plugin manifest, permissions, signing, compatibility, and security rules.'],
        'connector_sdk_docs' => ['label' => 'Connector SDK Documentation', 'route' => 'developers.docs.connectors', 'uri' => '/developers/docs/connectors', 'task_ids' => ['T12'], 'intent' => 'Document connector SDK boundaries, scopes, sync safety, and webhook expectations.'],
        'submission_checklist' => ['label' => 'Package Submission Checklist', 'route' => 'developers.submission-checklist', 'uri' => '/developers/submission-checklist', 'task_ids' => ['T13', 'T28', 'T29'], 'intent' => 'Show theme and plugin QA requirements before upload.'],
        'developer_listings' => ['label' => 'Developer Listing Management', 'route' => 'developers.listings', 'uri' => '/developers/listings', 'task_ids' => ['T14'], 'intent' => 'Explain listing management, review feedback, changelog, and support.'],
        'developer_sales' => ['label' => 'Developer Sales and Usage', 'route' => 'developers.sales', 'uri' => '/developers/sales', 'task_ids' => ['T15', 'T22', 'T30'], 'intent' => 'Show installs, usage, refunds, payout, and revenue share metrics.'],
        'developer_profile' => ['label' => 'Developer Profile and Creator Page', 'route' => 'developers.profile', 'uri' => '/developers/profile', 'task_ids' => ['T25'], 'intent' => 'Explain developer/creator identity, trust, certification, and public profile.'],
        'qa_center' => ['label' => 'Theme and Plugin QA Center', 'route' => 'developers.qa', 'uri' => '/developers/qa', 'task_ids' => ['T28', 'T29'], 'intent' => 'Unify theme QA and plugin security permission QA.'],
    ],
    'marketplace_lanes' => [
        ['key' => 'design_market', 'label' => 'Kabeeri Design Market', 'sells' => ['themes', 'templates', 'UI blocks', 'section kits', 'business kits'], 'route' => 'marketplace.themes.index'],
        ['key' => 'package_store', 'label' => 'Package Store', 'sells' => ['plugins', 'modules', 'connectors', 'AI skills', 'industry solutions'], 'route' => 'marketplace.plugins.index'],
        ['key' => 'developer_console', 'label' => 'Developer Console', 'sells' => ['submissions', 'review status', 'listings', 'usage', 'revenue'], 'route' => 'developers.portal'],
        ['key' => 'governance_console', 'label' => 'Governance Console', 'sells' => ['review', 'permissions', 'signing', 'suspension', 'audit'], 'route' => 'marketplace.governance'],
    ],
    'taxonomy' => [
        'theme_categories' => ['business website', 'service business', 'commerce', 'landing page', 'portfolio', 'academy', 'portal', 'enterprise'],
        'plugin_categories' => ['commerce', 'CRM', 'marketing', 'analytics', 'automation', 'integration', 'AI', 'security', 'industry solution'],
        'filters' => ['category', 'industry', 'app type', 'price type', 'RTL support', 'performance score', 'publisher trust', 'compatibility', 'license', 'support policy'],
        'sorts' => ['featured', 'newest', 'most installed', 'highest rated', 'best performance', 'lowest risk'],
    ],
    'themes' => [
        [
            'slug' => 'kabeeri-atlas',
            'name' => 'Kabeeri Atlas',
            'type' => 'Next.js theme',
            'category' => 'business website',
            'price_type' => 'pro',
            'publisher' => 'KABEERI Official',
            'performance_score' => 94,
            'supports_rtl' => true,
            'license' => 'single workspace or agency pack',
            'best_for' => 'Professional company, service business, and verified profile launch.',
            'components' => ['Hero', 'FeatureGrid', 'ServiceCards', 'LeadForm', 'TrustBadges', 'PricingTable'],
            'compatibility' => ['Laravel API contracts', 'Next.js App Router', 'mobile theme profile', 'RTL/LTR'],
            'qa' => ['manifest valid', 'RTL pass', 'responsive pass', 'SEO pass', 'API-only rendering'],
        ],
        [
            'slug' => 'mall-window',
            'name' => 'Mall Window',
            'type' => 'Listing theme',
            'category' => 'commerce',
            'price_type' => 'paid',
            'publisher' => 'Certified Creator',
            'performance_score' => 90,
            'supports_rtl' => true,
            'license' => 'per app',
            'best_for' => 'Product, service, course, travel, and talent listing pages.',
            'components' => ['ListingHero', 'FilterRail', 'CardGrid', 'InquiryPanel', 'TrustRibbon'],
            'compatibility' => ['Mall listing APIs', 'moderation signals', 'sponsored placement', 'RTL/LTR'],
            'qa' => ['listing schema valid', 'image ratio pass', 'accessibility pass', 'moderation-safe copy'],
        ],
        [
            'slug' => 'studio-ops',
            'name' => 'Studio Ops',
            'type' => 'Agency kit',
            'category' => 'portal',
            'price_type' => 'agency',
            'publisher' => 'KABEERI Labs',
            'performance_score' => 91,
            'supports_rtl' => true,
            'license' => 'agency subscription',
            'best_for' => 'Agencies that package repeatable client onboarding and delivery.',
            'components' => ['ClientPortal', 'ProjectTimeline', 'PackageSelector', 'SupportPanel'],
            'compatibility' => ['agency plan', 'partner storefront', 'client workspaces', 'support queue'],
            'qa' => ['multi-client isolation', 'permission copy', 'responsive pass', 'theme recipe pass'],
        ],
    ],
    'theme_recipes' => [
        ['project_type' => 'service business', 'app_type' => 'website + CRM', 'required' => ['CMS', 'Forms', 'CRM Leads'], 'recommended' => ['Quotations', 'Invoices', 'Mall listing'], 'preview' => 'Launch services, capture inquiries, quote, invoice, and publish trusted listing.'],
        ['project_type' => 'commerce starter', 'app_type' => 'store + content', 'required' => ['CMS', 'Products', 'Orders'], 'recommended' => ['Coupons', 'Payments placeholder', 'Mall products'], 'preview' => 'Start product sales without WooCommerce-style plugin sprawl.'],
        ['project_type' => 'agency client kit', 'app_type' => 'client workspace', 'required' => ['Themes', 'Templates', 'Forms'], 'recommended' => ['Partner flow', 'Support', 'Revenue share'], 'preview' => 'Repeatable implementation kit for agencies and certified creators.'],
    ],
    'plugins' => [
        [
            'slug' => 'commerce-pulse-pack',
            'name' => 'Commerce Pulse Pack',
            'package_type' => 'plugin bundle',
            'category' => 'commerce',
            'publisher' => 'KABEERI Official',
            'risk' => 'medium',
            'price_type' => 'business plan add-on',
            'permissions' => ['products.read', 'orders.read', 'orders.write', 'coupons.write'],
            'dependencies' => ['commerce-lite', 'payments-placeholder'],
            'compatibility' => ['Laravel 13', 'KABEERI Business plan', 'audit logs', 'rollback safe'],
            'support_policy' => 'Official support with migration notes and uninstall path.',
        ],
        [
            'slug' => 'rabet-trust-signals',
            'name' => 'Rabet Trust Signals',
            'package_type' => 'extension',
            'category' => 'security',
            'publisher' => 'Certified Creator',
            'risk' => 'low',
            'price_type' => 'verification add-on',
            'permissions' => ['company.read', 'verification.read', 'public_badges.write'],
            'dependencies' => ['rabet-profile'],
            'compatibility' => ['company context', 'moderation approval', 'public badge renderer'],
            'support_policy' => 'Creator support with platform review for badge changes.',
        ],
        [
            'slug' => 'crm-followup-automation',
            'name' => 'CRM Follow-up Automation',
            'package_type' => 'AI skill',
            'category' => 'automation',
            'publisher' => 'KABEERI Labs',
            'risk' => 'high',
            'price_type' => 'AI credits',
            'permissions' => ['leads.read', 'crm_activities.write', 'notifications.write', 'ai.suggest'],
            'dependencies' => ['CRM', 'AI policy', 'notification center'],
            'compatibility' => ['approval required for sensitive actions', 'rate limits', 'audit trail'],
            'support_policy' => 'Requires policy review and explicit automation limits.',
        ],
    ],
    'bundles' => [
        ['name' => 'Service Launch Bundle', 'bundle_type' => 'service business', 'includes' => ['forms', 'CRM leads', 'quotations', 'invoices', 'Mall listing sync'], 'risk' => 'medium'],
        ['name' => 'Growth Marketing Bundle', 'bundle_type' => 'marketing', 'includes' => ['landing builder', 'campaign tracking', 'lead source scoring', 'UTM reports'], 'risk' => 'medium'],
        ['name' => 'Integration Starter Bundle', 'bundle_type' => 'connector', 'includes' => ['connector SDK', 'webhook logs', 'conflict preview', 'rate limits'], 'risk' => 'high'],
    ],
    'developer_onboarding' => [
        ['n' => '01', 'title' => 'Choose identity', 'text' => 'Creator, developer, agency, certified creator, or official publisher.'],
        ['n' => '02', 'title' => 'Create publisher account', 'text' => 'Tie package ownership to organization, company, support email, and payout intent.'],
        ['n' => '03', 'title' => 'Build manifest', 'text' => 'Declare runtime, permissions, compatibility, dependencies, license, support, and changelog.'],
        ['n' => '04', 'title' => 'Run local checks', 'text' => 'Theme QA, plugin security, tests, accessibility, RTL, performance, and safe uninstall.'],
        ['n' => '05', 'title' => 'Submit for review', 'text' => 'Upload package, screenshots, docs, demo data, license, and support policy.'],
        ['n' => '06', 'title' => 'Publish and support', 'text' => 'After approval and signing, monitor installs, usage, refunds, reviews, and support obligations.'],
    ],
    'lifecycle_statuses' => [
        ['status' => 'draft', 'owner' => 'creator', 'next_action' => 'Complete manifest and local checks.'],
        ['status' => 'submitted', 'owner' => 'platform', 'next_action' => 'Queue automated checks.'],
        ['status' => 'under_review', 'owner' => 'reviewer', 'next_action' => 'Review permissions, compatibility, code, QA, docs, and support.'],
        ['status' => 'needs_changes', 'owner' => 'creator', 'next_action' => 'Address review findings and resubmit.'],
        ['status' => 'approved', 'owner' => 'platform', 'next_action' => 'Prepare signing and listing publication.'],
        ['status' => 'published', 'owner' => 'marketplace', 'next_action' => 'Monitor installs, reviews, usage, support, and incidents.'],
        ['status' => 'suspended', 'owner' => 'platform', 'next_action' => 'Disable install/update and explain risk.'],
        ['status' => 'deprecated', 'owner' => 'creator', 'next_action' => 'Show migration path and sunset timeline.'],
        ['status' => 'removed', 'owner' => 'platform', 'next_action' => 'Hide listing and keep audit trail.'],
    ],
    'manifest_fields' => [
        'theme' => ['id', 'name', 'version', 'runtime', 'components', 'sections', 'api_contracts', 'mobile_profile', 'rtl', 'seo', 'performance_budget', 'license', 'support'],
        'plugin' => ['id', 'name', 'version', 'package_type', 'permissions', 'dependencies', 'migrations', 'uninstall', 'webhooks', 'jobs', 'rate_limits', 'compatibility', 'license', 'support'],
        'connector' => ['id', 'provider', 'scopes', 'auth_type', 'sync_objects', 'webhooks', 'rate_limits', 'conflict_strategy', 'secrets_policy', 'rollback', 'support'],
    ],
    'permissions' => [
        ['scope' => 'content.read', 'risk' => 'low', 'explain' => 'Reads published app content only.'],
        ['scope' => 'orders.write', 'risk' => 'medium', 'explain' => 'Can create or update commerce orders.'],
        ['scope' => 'company.verification.write', 'risk' => 'high', 'explain' => 'Changes trust or verification signals and needs review.'],
        ['scope' => 'finance.journal.post', 'risk' => 'critical', 'explain' => 'Posts accounting records and must remain tightly controlled.'],
        ['scope' => 'ai.apply_sensitive_change', 'risk' => 'critical', 'explain' => 'Applies AI-suggested sensitive actions only after explicit approval.'],
    ],
    'compatibility_axes' => ['Laravel version', 'API contract version', 'plan entitlement', 'organization/company context', 'required modules', 'mobile profile', 'RTL/LTR', 'theme runtime', 'safe migrations', 'uninstall support'],
    'qa_checklists' => [
        'theme' => ['manifest validity', 'RTL/LTR pass', 'responsive pass', 'accessibility pass', 'SEO metadata', 'performance budget', 'demo import and rollback', 'API-only rendering', 'no business logic', 'mobile profile', 'license metadata'],
        'plugin' => ['declared permissions', 'declared dependencies', 'no hidden data access', 'safe migrations', 'safe uninstall', 'audit logs', 'rate limits', 'automated tests', 'security scan', 'performance impact', 'compatibility matrix', 'no secrets logging', 'signing', 'support policy'],
    ],
    'component_library' => [
        'runtime' => 'Next.js App Router + React components + TypeScript props + Tailwind tokens',
        'foundations' => ['tokens.css', 'direction provider', 'locale-aware typography', 'component prop contracts', 'section registry', 'manifest resolver'],
        'components' => ['Button', 'Card', 'Hero', 'FeatureGrid', 'PricingTable', 'FAQ', 'ProductCard', 'ServiceGrid', 'ProfileCard', 'LeadForm', 'InstallPermissionPanel', 'CompatibilityMatrix'],
        'mapping_rule' => 'Manifest section keys map to React components. Laravel provides data through APIs; themes do not own business logic.',
    ],
    'review_flow' => [
        ['gate' => 'Manifest validation', 'checks' => ['required fields', 'semver', 'runtime', 'license', 'support']],
        ['gate' => 'Automated QA', 'checks' => ['tests', 'RTL', 'responsive', 'accessibility', 'performance', 'security scan']],
        ['gate' => 'Permission review', 'checks' => ['scopes', 'dependencies', 'migrations', 'uninstall', 'secrets']],
        ['gate' => 'Manual review', 'checks' => ['screenshots', 'docs', 'demo data', 'support obligations', 'copy quality']],
        ['gate' => 'Signing and publish', 'checks' => ['signature', 'listing metadata', 'pricing', 'changelog', 'rollback']],
    ],
    'licensing' => [
        'plans' => [
            ['label' => 'Free', 'fee' => '0%', 'best_for' => 'Community packages and official starters.'],
            ['label' => 'Paid Theme', 'fee' => '20% platform share', 'best_for' => 'Commercial themes, templates, and business kits.'],
            ['label' => 'Plugin Subscription', 'fee' => '25% platform share', 'best_for' => 'Plugins with support and updates.'],
            ['label' => 'Agency Pack', 'fee' => '15% platform share', 'best_for' => 'Multi-client implementation kits.'],
            ['label' => 'Enterprise Contract', 'fee' => 'Custom', 'best_for' => 'Private packages, SLAs, audits, and procurement.'],
        ],
        'payout_signals' => ['gross sales', 'refunds', 'platform share', 'tax hold', 'support SLA', 'payout status'],
    ],
    'admin_routes' => [
        'filament.admin.resources.developer-marketplace-listings.index',
        'filament.admin.resources.marketplace-catalog-items.index',
        'filament.admin.resources.integration-connectors.index',
    ],
    'database_tables' => ['themes', 'theme_app_recipes', 'packages', 'plugin_bundles', 'plugin_bundle_items', 'marketplace_catalog_items', 'creator_profiles', 'developer_marketplace_listings', 'integration_connectors'],
    'release_gates' => [
        ['key' => 'v9_ready', 'label' => 'V9 foundation ready'],
        ['key' => 'v10_ready', 'label' => 'V10 admin ready'],
        ['key' => 'v11_ready', 'label' => 'V11 public bridge ready'],
        ['key' => 'routes_ready', 'label' => 'V12 public/developer routes registered'],
        ['key' => 'admin_routes_ready', 'label' => 'Marketplace admin resource routes registered'],
        ['key' => 'database_ready', 'label' => 'Marketplace database tables available'],
        ['key' => 'docs_ready', 'label' => 'V12 docs ready'],
        ['key' => 'smoke_tests_ready', 'label' => 'V12 smoke tests ready'],
        ['key' => 'tracker_synced', 'label' => 'V12 task tracker synced'],
    ],
];
