<?php

return [
    'version' => 'V13',
    'name' => 'KABEERI Mall, Customer Portal, Partner, and Network UX',
    'rules' => [
        'runtime' => 'Laravel Blade is the V13 bridge for external portals. Long-term themed public surfaces still move toward Next.js contracts.',
        'mall_vs_marketplace' => 'Kabeeri Mall is public discovery. Kabeeri Marketplace is internal extensions. Do not mix Mall leads with package install flows.',
        'trust_first' => 'Mall listings must explain verification, publication consent, moderation, reporting, claim/submit, and reputation before conversion.',
        'portal_progressive' => 'Customer portal starts with setup, theme/plugin choice, products/services quick setup, billing, team, and support.',
        'partner_measurable' => 'Agency, marketer, partner, and legal partner paths must show lead handoff, referrals, commissions, verification journey, and next actions.',
    ],
    'pages' => [
        'mall_home' => ['label' => 'KABEERI Mall Home', 'route' => 'mall.index', 'uri' => '/mall', 'task_ids' => ['T02', 'T22'], 'intent' => 'Public discovery for trusted listings, not extension installs.'],
        'mall_search' => ['label' => 'Mall Search and Filters', 'route' => 'mall.search', 'uri' => '/mall/search', 'task_ids' => ['T03'], 'intent' => 'Expose search categories, trust filters, and listing type filters.'],
        'mall_trust' => ['label' => 'Mall Trust and Moderation', 'route' => 'mall.trust', 'uri' => '/mall/trust', 'task_ids' => ['T23'], 'intent' => 'Explain verification badges, moderation, reports, and reputation.'],
        'mall_claim_report' => ['label' => 'Mall Claim Submit and Report', 'route' => 'mall.claim-report', 'uri' => '/mall/claim-report', 'task_ids' => ['T24'], 'intent' => 'Explain listing claim, submit interest, and report flow.'],
        'business_directory' => ['label' => 'Business Directory', 'route' => 'mall.businesses.index', 'uri' => '/mall/businesses', 'task_ids' => ['T04'], 'intent' => 'Discover published business profiles with trust signals.'],
        'products' => ['label' => 'Products', 'route' => 'mall.products.index', 'uri' => '/mall/products', 'task_ids' => ['T05'], 'intent' => 'Browse public product mirrors with consent and moderation context.'],
        'services' => ['label' => 'Services', 'route' => 'mall.services.index', 'uri' => '/mall/services', 'task_ids' => ['T06'], 'intent' => 'Browse service listings and lead inquiry paths.'],
        'courses' => ['label' => 'Courses', 'route' => 'mall.courses.index', 'uri' => '/mall/courses', 'task_ids' => ['T07'], 'intent' => 'Browse training and academy-adjacent offers.'],
        'talent' => ['label' => 'Talent', 'route' => 'mall.talent.index', 'uri' => '/mall/talent', 'task_ids' => ['T08', 'T25'], 'intent' => 'Browse professional profiles and public talent paths.'],
        'travel' => ['label' => 'Travel', 'route' => 'mall.travel.index', 'uri' => '/mall/travel', 'task_ids' => ['T09'], 'intent' => 'Browse travel and tourism public listings.'],
        'customer_dashboard' => ['label' => 'Customer Portal Dashboard', 'route' => 'customer.dashboard', 'uri' => '/customer', 'task_ids' => ['T10'], 'intent' => 'Give customers a guided launch dashboard.'],
        'customer_theme_plugins' => ['label' => 'Customer Theme and Plugin Selection', 'route' => 'customer.theme-plugins', 'uri' => '/customer/theme-plugins', 'task_ids' => ['T11'], 'intent' => 'Explain safe theme and plugin selection from a customer perspective.'],
        'customer_quick_setup' => ['label' => 'Customer Products and Services Quick Setup', 'route' => 'customer.quick-setup', 'uri' => '/customer/quick-setup', 'task_ids' => ['T12'], 'intent' => 'Guide customer products/services setup before Mall publication.'],
        'partner_landing' => ['label' => 'Partner Landing', 'route' => 'partners.landing', 'uri' => '/partners', 'task_ids' => ['T13'], 'intent' => 'Explain partner, agency, marketer, and legal partner paths.'],
        'agency_profile' => ['label' => 'Agency Profile Setup', 'route' => 'partners.agency-profile', 'uri' => '/partners/agency-profile', 'task_ids' => ['T14'], 'intent' => 'Guide agency accreditation, regions, services, and portfolio setup.'],
        'partner_storefront' => ['label' => 'Partner Storefront Builder', 'route' => 'partners.storefront', 'uri' => '/partners/storefront', 'task_ids' => ['T15', 'T26'], 'intent' => 'Explain storefront creation, catalog sharing, and lead handoff.'],
        'referral_dashboard' => ['label' => 'Referral Dashboard', 'route' => 'partners.referrals', 'uri' => '/partners/referrals', 'task_ids' => ['T16', 'T27'], 'intent' => 'Show referral pipeline and commission placeholders.'],
        'campaign_resources' => ['label' => 'Marketer Campaign Resources', 'route' => 'partners.campaigns', 'uri' => '/partners/campaigns', 'task_ids' => ['T17'], 'intent' => 'Give marketers assets, campaign paths, UTMs, and handoff rules.'],
        'network_academy' => ['label' => 'Work Network and Academy Portal', 'route' => 'network.academy', 'uri' => '/network', 'task_ids' => ['T18'], 'intent' => 'Introduce Work Network, Academy badges, and professional growth.'],
        'talent_path' => ['label' => 'Professional Profile Path', 'route' => 'network.talent-path', 'uri' => '/network/talent-path', 'task_ids' => ['T25'], 'intent' => 'Explain public talent console and professional profile journey.'],
        'legal_verification' => ['label' => 'Legal Partner Verification Journey', 'route' => 'partners.legal-verification', 'uri' => '/partners/legal-verification', 'task_ids' => ['T28'], 'intent' => 'Explain legal partner verification support and trust record journey.'],
    ],
    'mall_sections' => [
        'businesses' => ['label' => 'Business Directory', 'route' => 'mall.businesses.index', 'count_model' => 'App\Models\MallMirrorBusiness', 'status_column' => 'mirror_status', 'search_fields' => ['display_name', 'description'], 'trust' => 'BusinessProfile, Rabet identity, public contacts, publication consent.'],
        'products' => ['label' => 'Products', 'route' => 'mall.products.index', 'count_model' => 'App\Models\MallMirrorProduct', 'status_column' => 'mirror_status', 'search_fields' => ['product_name', 'description'], 'trust' => 'Consent mirror, price clarity, product attributes, report flow.'],
        'services' => ['label' => 'Services', 'route' => 'mall.services.index', 'count_model' => 'App\Models\MallMirrorService', 'status_column' => 'mirror_status', 'search_fields' => ['service_name', 'description', 'service_category'], 'trust' => 'Availability, category, lead request, moderation.'],
        'courses' => ['label' => 'Courses', 'route' => 'mall.courses.index', 'count_model' => 'App\Models\MallMirrorCourse', 'status_column' => 'mirror_status', 'search_fields' => ['course_name', 'description', 'training_type'], 'trust' => 'Training type, delivery mode, instructor info, Academy relation.'],
        'talent' => ['label' => 'Talent', 'route' => 'mall.talent.index', 'count_model' => 'App\Models\MallMirrorTalent', 'status_column' => 'mirror_status', 'search_fields' => ['display_name', 'headline', 'bio'], 'trust' => 'Professional profile, skills, location, availability, consent.'],
        'travel' => ['label' => 'Travel', 'route' => 'mall.travel.index', 'count_model' => 'App\Models\TravelTourismMallListing', 'status_column' => 'listing_status', 'search_fields' => ['title', 'description', 'destination'], 'trust' => 'Destination, availability, contact channels, report flow.'],
    ],
    'search_filters' => [
        'listing_type' => ['business', 'product', 'service', 'course', 'talent', 'travel'],
        'trust' => ['verified', 'publication consent', 'moderated', 'reported safe', 'recently refreshed'],
        'location' => ['local', 'national', 'remote', 'travel destination'],
        'intent' => ['buy', 'request service', 'learn', 'hire talent', 'claim listing', 'report issue'],
    ],
    'trust_badges' => [
        ['label' => 'Published with consent', 'meaning' => 'The listing is mirrored only after publication consent or eligible public sync.'],
        ['label' => 'Rabet verification', 'meaning' => 'Business or company identity can be connected to a verification request and trust record.'],
        ['label' => 'Moderation reviewed', 'meaning' => 'Flags, reports, and moderation cases can remove or limit risky listings.'],
        ['label' => 'Reputation snapshot', 'meaning' => 'Reviews and reputation signals are shown as context, not as blind guarantees.'],
    ],
    'claim_report_flow' => [
        ['step' => '01', 'title' => 'Find or submit listing', 'text' => 'Visitor finds a public listing or submits interest to claim/create one.'],
        ['step' => '02', 'title' => 'Prove relationship', 'text' => 'Owner, agency, or legal partner provides organization/company evidence.'],
        ['step' => '03', 'title' => 'Review and moderation', 'text' => 'Platform checks consent, verification, duplicate risk, and reported issues.'],
        ['step' => '04', 'title' => 'Connect to workspace', 'text' => 'Approved listing links to Organization, Company, Site, or Partner Storefront.'],
        ['step' => '05', 'title' => 'Manage and improve', 'text' => 'Owner updates content, monitors leads, responds to reviews, and keeps trust signals current.'],
    ],
    'customer_steps' => [
        ['n' => '01', 'title' => 'Workspace readiness', 'text' => 'Confirm organization, app/site, company context if needed, plan, and team.'],
        ['n' => '02', 'title' => 'Theme and plugin selection', 'text' => 'Choose safe themes/plugins with permissions, compatibility, and rollback explained.'],
        ['n' => '03', 'title' => 'Products/services setup', 'text' => 'Add products, services, contact methods, prices, availability, and lead forms.'],
        ['n' => '04', 'title' => 'Trust and Mall publication', 'text' => 'Review consent, moderation rules, Rabet/company verification, and listing visibility.'],
        ['n' => '05', 'title' => 'Launch and measure', 'text' => 'Track leads, referrals, reviews, support requests, and next growth actions.'],
    ],
    'partner_paths' => [
        'agency' => ['label' => 'Agency Partner', 'benefit' => 'Create accredited profile, storefront, service kits, and client handoff workflow.', 'route' => 'partners.agency-profile'],
        'marketer' => ['label' => 'Marketer', 'benefit' => 'Use campaign assets, referrals, UTM tracking, lead handoff, and commission placeholders.', 'route' => 'partners.campaigns'],
        'storefront' => ['label' => 'Partner Storefront', 'benefit' => 'Publish services, packages, selected catalog shares, and managed lead intake.', 'route' => 'partners.storefront'],
        'legal' => ['label' => 'Legal Verification Partner', 'benefit' => 'Support verification requests, document review, and trust record workflows.', 'route' => 'partners.legal-verification'],
    ],
    'referral_metrics' => [
        ['label' => 'Referral code', 'value' => 'KBR-PARTNER-001'],
        ['label' => 'Qualified leads', 'value' => 'CRM handoff'],
        ['label' => 'Commission', 'value' => 'Placeholder until billing settlement'],
        ['label' => 'Payout status', 'value' => 'Pending policy'],
    ],
    'campaign_resources' => [
        'landing page copy',
        'audience path cards',
        'UTM rules',
        'demo request script',
        'Rabet trust explainer',
        'Mall listing claim script',
        'partner storefront kit',
    ],
    'network' => [
        'academy_badges' => ['Kabeeri Starter', 'Verified Creator', 'Mall Trust Guide', 'Partner Sales Basics'],
        'work_paths' => ['Professional profile', 'Talent listing', 'Agency role', 'Creator profile', 'Legal partner path'],
        'quality_rules' => ['public consent', 'skills evidence', 'badge criteria', 'moderation safety', 'report flow'],
    ],
    'legal_verification_steps' => [
        ['step' => '01', 'title' => 'Request intake', 'text' => 'Business submits verification need, documents, and company context.'],
        ['step' => '02', 'title' => 'Legal partner review', 'text' => 'Legal partner checks documents without exposing sensitive details publicly.'],
        ['step' => '03', 'title' => 'Platform decision', 'text' => 'Platform records verification outcome, audit trail, and trust badge eligibility.'],
        ['step' => '04', 'title' => 'Public trust record', 'text' => 'Mall and business profile show approved trust signals only.'],
    ],
    'database_tables' => [
        'mall_mirror_businesses',
        'mall_mirror_products',
        'mall_mirror_services',
        'mall_mirror_courses',
        'mall_mirror_talent',
        'travel_tourism_mall_listings',
        'mall_publication_consents',
        'reviews',
        'reputation_snapshots',
        'moderation_cases',
        'moderation_flags',
        'agency_partner_profiles',
        'partner_storefronts',
        'growth_referrals',
        'academy_badges',
        'legal_partner_profiles',
    ],
    'admin_routes' => [
        'filament.admin.resources.moderation-cases.index',
        'filament.admin.resources.reviews.index',
        'filament.admin.resources.agency-partner-profiles.index',
        'filament.admin.resources.partner-storefronts.index',
    ],
    'release_gates' => [
        ['key' => 'v9_ready', 'label' => 'V9 foundation ready'],
        ['key' => 'v10_ready', 'label' => 'V10 admin ready'],
        ['key' => 'v11_ready', 'label' => 'V11 public ready'],
        ['key' => 'v12_ready', 'label' => 'V12 marketplace ready'],
        ['key' => 'routes_ready', 'label' => 'V13 external routes registered'],
        ['key' => 'mall_routes_ready', 'label' => 'Existing Mall routes still registered'],
        ['key' => 'admin_routes_ready', 'label' => 'Moderation/review/partner admin routes registered'],
        ['key' => 'database_ready', 'label' => 'Mall and partner tables available'],
        ['key' => 'docs_ready', 'label' => 'V13 docs ready'],
        ['key' => 'smoke_tests_ready', 'label' => 'V13 smoke tests ready'],
        ['key' => 'tracker_synced', 'label' => 'V13 task tracker synced'],
    ],
];
