<?php

return [
    'version' => 'V16',
    'name' => 'kabeeri Customer Web Auth, Guided Onboarding, App Builder, and Workspace Runtime',
    'rules' => [
        'entry' => 'Public visitors enter through /start, choose an audience path, then authenticate only when they are ready to create a workspace.',
        'auth_scope' => 'Customer web auth marks its session surface; /admin/login and /platform-admin/login reset customer sessions before Filament admin login.',
        'workspace' => 'A customer workspace creates User, Organization, optional Company, first Site/App, selected Theme, theme settings, and starter content.',
        'theme_install' => 'Theme install must be explicit, app-type compatible, reversible later, and must not execute hidden package code.',
        'fixed_permalink' => 'Every customer-created app receives one globally unique username permalink that is never changed after creation.',
        'roles' => 'Customers can add capabilities such as marketer, creator, developer, agency, or implementation builder request without becoming platform admins.',
    ],
    'routes' => [
        ['name' => 'customer.start', 'uri' => '/start', 'label' => 'Customer Start'],
        ['name' => 'login', 'uri' => '/login', 'label' => 'Customer Login'],
        ['name' => 'register', 'uri' => '/register', 'label' => 'Customer Register'],
        ['name' => 'customer.onboarding', 'uri' => '/customer/onboarding', 'label' => 'Guided Onboarding'],
        ['name' => 'customer.onboarding.store', 'uri' => '/customer/onboarding', 'label' => 'Provision Workspace'],
        ['name' => 'customer.workspace', 'uri' => '/customer/dashboard', 'label' => 'Customer Dashboard'],
        ['name' => 'customer.apps.index', 'uri' => '/customer/apps', 'label' => 'Manage Customer Apps'],
        ['name' => 'customer.apps.create', 'uri' => '/customer/apps/create', 'label' => 'Create Customer App'],
        ['name' => 'customer.apps.store', 'uri' => '/customer/apps', 'label' => 'Store Customer App'],
        ['name' => 'customer.apps.edit', 'uri' => '/customer/apps/{username}/edit', 'label' => 'Edit Customer App'],
        ['name' => 'customer.apps.update', 'uri' => '/customer/apps/{username}', 'label' => 'Update Customer App'],
        ['name' => 'customer.apps.destroy', 'uri' => '/customer/apps/{username}', 'label' => 'Trash Customer App'],
        ['name' => 'customer.apps.trash', 'uri' => '/customer/apps/trash', 'label' => 'Customer App Trash'],
        ['name' => 'customer.apps.restore', 'uri' => '/customer/apps/trash/{username}/restore', 'label' => 'Restore Customer App'],
        ['name' => 'customer.apps.schedule-delete', 'uri' => '/customer/apps/trash/{username}/schedule-delete', 'label' => 'Schedule Customer App Delete'],
        ['name' => 'customer.apps.themes', 'uri' => '/customer/apps/{username}/themes', 'label' => 'Customer App Themes'],
        ['name' => 'customer.apps.themes.update', 'uri' => '/customer/apps/{username}/themes', 'label' => 'Switch Customer App Theme'],
        ['name' => 'customer.apps.plugins', 'uri' => '/customer/apps/{username}/plugins', 'label' => 'Customer App Plugins'],
        ['name' => 'customer.apps.plugins.install', 'uri' => '/customer/apps/{username}/plugins/{package}', 'label' => 'Install Customer App Plugin'],
        ['name' => 'customer.apps.plugins.deactivate', 'uri' => '/customer/apps/{username}/plugins/{package}/deactivate', 'label' => 'Deactivate Customer App Plugin'],
        ['name' => 'customer.apps.plugins.activate', 'uri' => '/customer/apps/{username}/plugins/{package}/activate', 'label' => 'Activate Customer App Plugin'],
        ['name' => 'customer.apps.show', 'uri' => '/customer/apps/{username}', 'label' => 'Customer App Detail'],
        ['name' => 'public.site.show', 'uri' => '/app/{username}', 'label' => 'Public App Permalink'],
        ['name' => 'public.content-entry.show', 'uri' => '/app/{username}/{contentEntry}', 'label' => 'Public App Page'],
        ['name' => 'customer.capabilities.update', 'uri' => '/customer/profile/capabilities', 'label' => 'Capabilities Upgrade'],
    ],
    'audience_paths' => [
        'business_owner' => [
            'label' => 'Business Owner',
            'headline' => 'Launch a website, store, or service presence and grow into operations.',
            'default_app_type' => 'website',
            'creates_company' => true,
            'benefits' => ['kabeeri App', 'CRM Leads', 'Theme install', 'Mall visibility later'],
        ],
        'store_owner' => [
            'label' => 'Store Owner',
            'headline' => 'Start a lightweight store that can grow without plugin chaos.',
            'default_app_type' => 'store',
            'creates_company' => true,
            'benefits' => ['Products', 'Orders foundation', 'Coupons', 'Mall products later'],
        ],
        'service_business' => [
            'label' => 'Service Business',
            'headline' => 'Show services, capture leads, and grow into quotations and operations.',
            'default_app_type' => 'service_business',
            'creates_company' => true,
            'benefits' => ['Services', 'Lead forms', 'Quotations later', 'CRM'],
        ],
        'creator_developer' => [
            'label' => 'Creator / Developer',
            'headline' => 'Start as a customer, then add a path to build and sell themes or plugins.',
            'default_app_type' => 'portfolio',
            'creates_company' => false,
            'benefits' => ['Profile', 'Developer path', 'Marketplace publishing later'],
        ],
        'marketer_partner' => [
            'label' => 'Marketer / Partner',
            'headline' => 'Start partner files, campaigns, referrals, and storefront potential.',
            'default_app_type' => 'landing',
            'creates_company' => false,
            'benefits' => ['Referral path', 'Campaigns', 'Partner storefront later'],
        ],
        'needs_builder' => [
            'label' => 'I need a builder',
            'headline' => 'Request a kabeeri Builder to help create the app, company, and content.',
            'default_app_type' => 'website',
            'creates_company' => true,
            'benefits' => ['Builder request', 'Guided setup', 'Implementation partner handoff'],
        ],
    ],
    'app_types' => [
        'website' => ['label' => 'Website', 'intent' => 'Pages, content, SEO, and contact forms.'],
        'store' => ['label' => 'Store', 'intent' => 'Products, orders, coupons, and Mall readiness later.'],
        'service_business' => ['label' => 'Service Business', 'intent' => 'Services, lead capture, and quotations later.'],
        'landing' => ['label' => 'Landing Page', 'intent' => 'Campaign, offer, or fast funnel.'],
        'portfolio' => ['label' => 'Portfolio / Profile', 'intent' => 'Personal, creator, or developer profile.'],
        'portal' => ['label' => 'Portal', 'intent' => 'Customer or team portal over time.'],
    ],
    'starter_themes' => [
        [
            'name' => 'kabeeri Atlas',
            'slug' => 'kabeeri-atlas',
            'category' => 'business website',
            'app_types' => ['website', 'service_business', 'portal'],
            'price_type' => 'free',
            'performance_score' => 94,
            'supports_rtl' => true,
            'supports_dark_mode' => false,
            'publisher' => 'kabeeri Official',
            'manifest' => ['sections' => ['hero', 'services', 'trust', 'lead_form'], 'runtime' => 'blade-bridge-next-ready'],
            'settings' => ['palette' => 'sand-olive', 'home_layout' => 'service-led', 'lead_capture' => true],
        ],
        [
            'name' => 'Mall Window',
            'slug' => 'mall-window',
            'category' => 'commerce',
            'app_types' => ['store', 'service_business'],
            'price_type' => 'free',
            'performance_score' => 90,
            'supports_rtl' => true,
            'supports_dark_mode' => false,
            'publisher' => 'kabeeri Official',
            'manifest' => ['sections' => ['catalog', 'filters', 'trust_badges', 'inquiry'], 'runtime' => 'blade-bridge-next-ready'],
            'settings' => ['palette' => 'market-clay', 'home_layout' => 'catalog-led', 'mall_ready' => true],
        ],
        [
            'name' => 'Launch Loom',
            'slug' => 'launch-loom',
            'category' => 'landing page',
            'app_types' => ['landing', 'portfolio', 'website'],
            'price_type' => 'free',
            'performance_score' => 92,
            'supports_rtl' => true,
            'supports_dark_mode' => true,
            'publisher' => 'kabeeri Official',
            'manifest' => ['sections' => ['campaign_hero', 'proof', 'pricing', 'cta'], 'runtime' => 'blade-bridge-next-ready'],
            'settings' => ['palette' => 'night-gold', 'home_layout' => 'conversion-led', 'campaign_mode' => true],
        ],
    ],
    'capabilities' => [
        'customer_owner' => ['label' => 'Customer Owner', 'description' => 'Manages workspace, app, and subscription.'],
        'developer_creator' => ['label' => 'Developer / Creator', 'description' => 'Wants to build themes, plugins, or assets for sale later.'],
        'marketer_partner' => ['label' => 'Marketer / Partner', 'description' => 'Wants referrals, campaigns, and lead handoff.'],
        'implementation_builder' => ['label' => 'kabeeri Builder', 'description' => 'Wants to help customers build apps, companies, and content.'],
        'needs_builder_help' => ['label' => 'Needs Builder Help', 'description' => 'Customer wants someone to build the platform path for them.'],
    ],
    'dashboard_cards' => [
        ['key' => 'app', 'label' => 'My App', 'text' => 'Open your app, theme, and starter pages.'],
        ['key' => 'theme', 'label' => 'Theme', 'text' => 'Review installed theme and settings.'],
        ['key' => 'modules', 'label' => 'Features', 'text' => 'Add commerce, CRM, or Mall visibility later.'],
        ['key' => 'team', 'label' => 'Team', 'text' => 'Invite your team and define permissions later.'],
        ['key' => 'builder', 'label' => 'Builder Help', 'text' => 'Request someone to help build your app and company setup.'],
        ['key' => 'marketplace', 'label' => 'Marketplace', 'text' => 'Discover compatible themes and plugins.'],
    ],
    'release_gates' => [
        ['key' => 'routes_ready', 'label' => 'V16 customer routes registered'],
        ['key' => 'auth_ready', 'label' => 'Customer login/register/logout works'],
        ['key' => 'onboarding_ready', 'label' => 'Onboarding provisions workspace and site'],
        ['key' => 'theme_install_ready', 'label' => 'Theme install activates site theme and settings'],
        ['key' => 'dashboard_ready', 'label' => 'Authenticated customer dashboard renders'],
        ['key' => 'capabilities_ready', 'label' => 'Profile capabilities can be upgraded'],
        ['key' => 'docs_ready', 'label' => 'V16 docs exist'],
        ['key' => 'tracker_synced', 'label' => 'V16 task tracker synced'],
    ],
];
