<?php

return [
    'version' => 'V9',
    'name' => 'kabeeri UI Foundation, Navigation, and Frontend Runtime',
    'decision' => [
        'public_runtime_target' => 'Next.js + React + TypeScript + Tailwind',
        'admin_runtime' => 'Filament + Livewire inside Laravel',
        'backend_runtime' => 'Laravel API-first modular monolith',
        'blade_policy' => 'Blade is allowed as a bridge/fallback only until the Next.js public theme runtime is scaffolded.',
        'mobile_runtime' => 'Flutter shell consuming mobile config, theme, and API manifest endpoints.',
        'desktop_runtime' => 'Electron + React + TypeScript + local SQLite sync client consuming Laravel APIs.',
    ],
    'boundaries' => [
        'laravel_backend' => [
            'owns' => ['domain logic', 'database', 'RBAC and policies', 'jobs', 'events', 'REST JSON APIs', 'OpenAPI-ready contracts'],
            'must_not_own' => ['long-term commercial public theme rendering', 'React theme internals'],
        ],
        'filament_admin' => [
            'owns' => ['internal admin workspaces', 'review queues', 'operations dashboards', 'governance screens', 'safe CRUD flows'],
            'must_show' => ['current context', 'allowed actions', 'blocked actions', 'work needing attention'],
        ],
        'blade_bridge' => [
            'owns' => ['current root dashboard', 'current Mall fallback pages', 'current public content fallback rendering'],
            'expiry_rule' => 'Do not expand Blade into the permanent public theme marketplace runtime.',
        ],
        'next_public_runtime' => [
            'owns' => ['public marketing', 'commercial themes', 'theme components', 'section kits', 'SEO-first pages', 'theme manifests'],
            'reads_from' => ['Laravel REST JSON APIs', 'OpenAPI contracts', 'public/private scoped endpoints'],
        ],
        'flutter_mobile' => [
            'owns' => ['mobile shell UI', 'mobile onboarding', 'profile rendering from mobile theme profile'],
            'reads_from' => ['api/mobile/config', 'api/mobile/theme', 'api/mobile/manifest'],
        ],
        'electron_desktop' => [
            'owns' => ['desktop shell UI', 'local sync state', 'outbox visibility'],
            'reads_from' => ['api/desktop/register', 'api/desktop/sync/pull', 'api/desktop/sync/push-dry-run'],
        ],
    ],
    'design_tokens' => [
        'colors' => [
            'ink' => '#17130d',
            'paper' => '#f3e5ab',
            'sand' => '#f2ddb8',
            'bronze' => '#c98a2e',
            'olive' => '#3f5e47',
            'sage' => '#78956f',
            'clay' => '#9a5539',
            'date' => '#20170f',
            'sky' => '#2f5f73',
            'success' => '#2f7d46',
            'warning' => '#a76b1f',
            'danger' => '#9b3f30',
            'neutral' => '#756a5e',
        ],
        'typography' => [
            'arabic_first' => ['IBM Plex Sans Arabic', 'Almarai'],
            'latin_fallback' => ['Instrument Sans', 'ui-sans-serif', 'system-ui'],
            'scale' => [
                'display' => 'clamp(3rem, 8vw, 6.5rem)',
                'h1' => 'clamp(2.4rem, 5vw, 5rem)',
                'h2' => 'clamp(2rem, 3vw, 3.5rem)',
                'h3' => '1.55rem',
                'body' => '1rem',
                'lead' => 'clamp(1.08rem, 1.6vw, 1.35rem)',
                'label' => '.82rem',
            ],
        ],
        'spacing' => [
            'xs' => '0.5rem',
            'sm' => '0.75rem',
            'md' => '1rem',
            'lg' => '1.5rem',
            'xl' => '2rem',
            '2xl' => '3rem',
            '3xl' => '4.5rem',
        ],
        'radius' => [
            'sm' => '0.75rem',
            'md' => '1.125rem',
            'lg' => '1.75rem',
            'xl' => '2.5rem',
            'pill' => '999px',
        ],
        'shadow' => [
            'soft' => '0 18px 50px rgba(69,43,16,.10)',
            'strong' => '0 30px 90px rgba(69,43,16,.18)',
            'focus' => '0 0 0 4px rgba(201,138,46,.25)',
        ],
        'breakpoints' => [
            'mobile' => '0-760px',
            'tablet' => '761-1180px',
            'desktop' => '1181px+',
        ],
        'motion' => [
            'principle' => 'Use purposeful page-load and disclosure motion only; no decorative noise.',
            'duration_fast' => '160ms',
            'duration_base' => '240ms',
            'duration_slow' => '520ms',
        ],
    ],
    'component_standards' => [
        'Button', 'Input', 'Select', 'Textarea', 'Card', 'Badge', 'Tabs', 'Accordion', 'Modal', 'Dropdown', 'Navbar', 'Footer', 'Hero', 'ServicesGrid', 'ProductCard', 'CourseCard', 'BookingForm', 'ReviewCard', 'PricingTable', 'FAQ', 'CTASection', 'Gallery', 'MapBlock', 'ProfileCard',
    ],
    'admin_spaces' => [
        'personal' => [
            'label' => 'Personal Space',
            'context' => 'user',
            'primary_jobs' => ['profile', 'notifications', 'personal tasks'],
            'resource_groups' => ['People'],
        ],
        'organization' => [
            'label' => 'Organization Workspace',
            'context' => 'organization',
            'primary_jobs' => ['workspace health', 'team access', 'apps/sites overview'],
            'resource_groups' => ['Organizations', 'Core', 'Apps'],
        ],
        'site' => [
            'label' => 'kabeeri App / Site Admin',
            'context' => 'site',
            'primary_jobs' => ['content', 'menus', 'SEO', 'forms', 'media', 'theme settings'],
            'resource_groups' => ['Content', 'Media', 'Apps'],
        ],
        'company_rabet' => [
            'label' => 'Company Admin / Rabet OS',
            'context' => 'company',
            'primary_jobs' => ['business profile', 'verification', 'contacts', 'trust'],
            'resource_groups' => ['Rabet Foundation', 'CRM'],
        ],
        'commerce' => [
            'label' => 'Commerce Admin',
            'context' => 'site_or_company',
            'primary_jobs' => ['products', 'orders', 'coupons', 'payments'],
            'resource_groups' => ['Commerce'],
        ],
        'erp' => [
            'label' => 'ERP Admin',
            'context' => 'company',
            'primary_jobs' => ['inventory', 'purchasing', 'finance', 'workflows'],
            'resource_groups' => ['Inventory & Purchasing', 'Finance', 'Workflows'],
        ],
        'mall' => [
            'label' => 'kabeeri Mall Console',
            'context' => 'public_listing',
            'primary_jobs' => ['publication consent', 'moderation', 'trust', 'mirrors'],
            'resource_groups' => ['V4 Mall', 'V4 Marketplace'],
        ],
        'talent' => [
            'label' => 'Talent Console',
            'context' => 'professional_profile',
            'primary_jobs' => ['profiles', 'badges', 'academy', 'work network'],
            'resource_groups' => ['V4 Partners', 'People'],
        ],
        'teams' => [
            'label' => 'kabeeri Teams',
            'context' => 'team',
            'primary_jobs' => ['projects', 'tasks', 'approvals', 'activity'],
            'resource_groups' => ['People', 'Workflows'],
        ],
        'developer' => [
            'label' => 'Developer Console',
            'context' => 'publisher_account',
            'primary_jobs' => ['packages', 'plugin bundles', 'marketplace listings', 'review status'],
            'resource_groups' => ['V4 Marketplace', 'Integrations'],
        ],
        'billing' => [
            'label' => 'Billing Console',
            'context' => 'organization_or_company',
            'primary_jobs' => ['plans', 'usage', 'entitlements', 'invoices'],
            'resource_groups' => ['Freemium', 'Finance'],
        ],
        'platform' => [
            'label' => 'Platform Admin',
            'context' => 'global',
            'primary_jobs' => ['system health', 'feature flags', 'security', 'release readiness'],
            'resource_groups' => ['System', 'Enterprise', 'Mobile', 'Desktop'],
        ],
    ],
    'admin_roles' => [
        'platform_owner' => ['entry_space' => 'platform', 'needs' => ['system check', 'task tracker', 'release gates']],
        'support_admin' => ['entry_space' => 'platform', 'needs' => ['activity timeline', 'customer context', 'safe impersonation request path']],
        'organization_owner' => ['entry_space' => 'organization', 'needs' => ['workspace setup', 'team permissions', 'billing overview']],
        'site_admin' => ['entry_space' => 'site', 'needs' => ['content publishing', 'menus', 'SEO', 'theme preview']],
        'company_admin' => ['entry_space' => 'company_rabet', 'needs' => ['verification', 'contacts', 'business profile']],
        'commerce_admin' => ['entry_space' => 'commerce', 'needs' => ['orders', 'products', 'payments']],
        'developer' => ['entry_space' => 'developer', 'needs' => ['manifest status', 'package reviews', 'revenue visibility']],
        'billing_admin' => ['entry_space' => 'billing', 'needs' => ['plan limits', 'usage', 'invoices']],
        'security_admin' => ['entry_space' => 'platform', 'needs' => ['audit events', 'blocked actions', 'risk queues']],
    ],
    'external_audiences' => [
        'business_owner' => ['path' => 'Website -> commerce -> CRM -> operations -> Mall visibility', 'first_question' => 'How do I launch and grow without WordPress/WooCommerce complexity?'],
        'agency' => ['path' => 'Client apps -> reusable kits -> service delivery -> partner revenue', 'first_question' => 'How do I deliver sites and operations faster for clients?'],
        'developer_creator' => ['path' => 'Developer profile -> package/theme -> review -> signing -> marketplace revenue', 'first_question' => 'How can I build and sell extensions safely?'],
        'marketer_partner' => ['path' => 'Referral -> campaign -> lead handoff -> revenue visibility', 'first_question' => 'How do I earn from bringing customers and campaigns?'],
        'enterprise_buyer' => ['path' => 'Governance -> security -> integrations -> GRC/BI -> enterprise contract', 'first_question' => 'Can this platform govern teams, data, and integrations safely?'],
        'mall_visitor' => ['path' => 'Discover -> compare -> trust badges -> lead/order/contact', 'first_question' => 'Can I trust this business, product, service, or professional?'],
    ],
    'route_registry' => [
        'current_laravel_public' => [
            ['key' => 'root_dashboard', 'route' => 'home', 'uri' => '/', 'runtime' => 'blade_bridge', 'owner' => 'platform', 'status' => 'current'],
            ['key' => 'mall_home', 'route' => 'mall.index', 'uri' => '/mall', 'runtime' => 'blade_bridge', 'owner' => 'mall', 'status' => 'current'],
            ['key' => 'mall_businesses', 'route' => 'mall.businesses.index', 'uri' => '/mall/businesses', 'runtime' => 'blade_bridge', 'owner' => 'mall', 'status' => 'current'],
            ['key' => 'mall_products', 'route' => 'mall.products.index', 'uri' => '/mall/products', 'runtime' => 'blade_bridge', 'owner' => 'mall', 'status' => 'current'],
            ['key' => 'mall_services', 'route' => 'mall.services.index', 'uri' => '/mall/services', 'runtime' => 'blade_bridge', 'owner' => 'mall', 'status' => 'current'],
            ['key' => 'mall_courses', 'route' => 'mall.courses.index', 'uri' => '/mall/courses', 'runtime' => 'blade_bridge', 'owner' => 'mall', 'status' => 'current'],
            ['key' => 'mall_talent', 'route' => 'mall.talent.index', 'uri' => '/mall/talent', 'runtime' => 'blade_bridge', 'owner' => 'mall', 'status' => 'current'],
            ['key' => 'mall_travel', 'route' => 'mall.travel.index', 'uri' => '/mall/travel', 'runtime' => 'blade_bridge', 'owner' => 'mall', 'status' => 'current'],
            ['key' => 'public_content_entry', 'route' => 'public.content-entry.show', 'uri' => '/app/{username}/{contentEntry}', 'runtime' => 'blade_bridge', 'owner' => 'cms', 'status' => 'current'],
            ['key' => 'language_switch', 'route' => 'language.switch', 'uri' => '/language/{locale}', 'runtime' => 'blade_bridge', 'owner' => 'localization', 'status' => 'current'],
        ],
        'current_admin' => [
            ['key' => 'admin_dashboard', 'route' => 'filament.admin.pages.dashboard', 'uri' => '/admin', 'runtime' => 'filament_admin', 'space' => 'platform', 'status' => 'current'],
            ['key' => 'admin_login_entry', 'route' => 'admin.login.entry', 'uri' => '/platform-admin/login', 'runtime' => 'laravel_bridge', 'space' => 'platform', 'status' => 'current'],
            ['key' => 'admin_login', 'route' => 'filament.admin.auth.login', 'uri' => '/admin/login', 'runtime' => 'filament_admin', 'space' => 'platform', 'status' => 'current'],
            ['key' => 'plans', 'route' => 'filament.admin.resources.plans.index', 'uri' => '/admin/plans', 'runtime' => 'filament_admin', 'space' => 'billing', 'status' => 'current'],
            ['key' => 'organizations', 'route' => 'filament.admin.resources.organizations.index', 'uri' => '/admin/organizations', 'runtime' => 'filament_admin', 'space' => 'organization', 'status' => 'current'],
            ['key' => 'sites', 'route' => 'filament.admin.resources.sites.index', 'uri' => '/admin/sites', 'runtime' => 'filament_admin', 'space' => 'site', 'status' => 'current'],
            ['key' => 'companies', 'route' => 'filament.admin.resources.companies.index', 'uri' => '/admin/companies', 'runtime' => 'filament_admin', 'space' => 'company_rabet', 'status' => 'current'],
        ],
        'api_contract_candidates' => [
            ['key' => 'mobile_manifest', 'route' => 'mobile.manifest', 'uri' => '/api/mobile/manifest', 'runtime' => 'api_contract', 'consumer' => 'flutter_mobile', 'status' => 'current'],
            ['key' => 'mobile_config', 'route' => 'mobile.config', 'uri' => '/api/mobile/config', 'runtime' => 'api_contract', 'consumer' => 'flutter_mobile', 'status' => 'current'],
            ['key' => 'mobile_theme', 'route' => 'mobile.theme', 'uri' => '/api/mobile/theme', 'runtime' => 'api_contract', 'consumer' => 'flutter_mobile', 'status' => 'current'],
            ['key' => 'desktop_register', 'route' => 'desktop.register', 'uri' => '/api/desktop/register', 'runtime' => 'api_contract', 'consumer' => 'electron_desktop', 'status' => 'current'],
            ['key' => 'desktop_pull', 'route' => 'desktop.sync.pull', 'uri' => '/api/desktop/sync/pull', 'runtime' => 'api_contract', 'consumer' => 'electron_desktop', 'status' => 'current'],
            ['key' => 'public_web_manifest', 'route' => 'public-web.manifest', 'uri' => '/api/public-web/manifest', 'runtime' => 'api_contract', 'consumer' => 'next_public_runtime', 'status' => 'current_v15'],
        ],
        'planned_next_public' => [
            ['key' => 'marketing_home', 'uri' => '/', 'runtime' => 'next_public_runtime', 'status' => 'planned_v11'],
            ['key' => 'audience_selector', 'uri' => '/for', 'runtime' => 'next_public_runtime', 'status' => 'planned_v11'],
            ['key' => 'pricing', 'uri' => '/pricing', 'runtime' => 'next_public_runtime', 'status' => 'planned_v11'],
            ['key' => 'developer_marketplace', 'uri' => '/marketplace', 'runtime' => 'next_public_runtime', 'status' => 'planned_v12'],
            ['key' => 'developer_portal', 'uri' => '/developers', 'runtime' => 'next_public_runtime', 'status' => 'planned_v12'],
            ['key' => 'public_mall', 'uri' => '/mall', 'runtime' => 'next_public_runtime', 'status' => 'planned_v13'],
        ],
    ],
    'rtl_accessibility_responsive' => [
        'rtl' => ['Use logical CSS properties', 'Do not hard-code left/right when inline-start/end is intended', 'Arabic content is primary, English is fallback'],
        'accessibility' => ['Semantic HTML first', 'Visible focus states', 'Keyboard reachable navigation', 'Contrast-safe tokens', 'Do not rely on color alone'],
        'responsive' => ['Mobile-first content hierarchy', 'No horizontal scroll at 360px', 'Sticky elements must gracefully collapse', 'Tables need card/list fallback'],
        'copy' => ['Use kabeeri App for public site/app copy', 'Use Site only for technical/admin database context', 'Do not expose every module at once to public visitors'],
    ],
    'smoke_strategy' => [
        'route_rendering' => ['/', '/admin/login', '/mall', '/mall/products', '/api/mobile/manifest'],
        'visual_contracts' => ['RTL direction', 'primary navigation visible', 'mobile no-overflow', 'focus states visible'],
        'data_contracts' => ['task tracker summary reads JSON tasks', 'route registry current routes exist', 'design tokens are present'],
        'commands' => ['php artisan test --filter=V9UiFoundationTest', 'php artisan test --filter=RootDashboardPageTest', 'vendor/bin/pint --test', 'npm run build'],
    ],
    'progressive_disclosure' => [
        'public' => 'Tell one audience journey at a time. Start with website/CMS, then commerce, trust, operations, Mall, and platform growth.',
        'admin' => 'Show the active context first. Hide advanced modules until enabled, relevant, or permission-approved.',
        'developer' => 'Show package lifecycle state and next required action instead of every governance detail at once.',
    ],
    'permission_aware_navigation' => [
        'rule' => 'UI visibility is a convenience, not security. Backend policies and permissions remain mandatory.',
        'blocked_action_copy' => 'Explain why the action is unavailable and what permission, plan, review, or context unlocks it.',
        'sensitive_actions' => ['billing.manage', 'company.verification.approve', 'finance.journal.post', 'users.role.assign', 'plugin.install', 'ai.apply_sensitive_change'],
    ],
    'naming_rules' => [
        'app_vs_site' => 'Use kabeeri App for customer-facing website/store/landing/blog/portal copy. Use Site in admin technical context.',
        'organization' => 'Workspace/admin scope.',
        'company' => 'Legal/business entity.',
        'business_profile' => 'Public Mall appearance of a company/business.',
        'professional_profile' => 'Public talent appearance of a person.',
    ],
    'marketplace_vs_mall' => [
        'marketplace' => ['audience' => 'owners, admins, developers, agencies', 'sells' => ['themes', 'plugins', 'connectors', 'AI skills', 'industry solutions'], 'core_flow' => 'review -> permissions -> signing -> install/update'],
        'mall' => ['audience' => 'public visitors, buyers, companies, talent', 'lists' => ['businesses', 'services', 'products', 'courses', 'talent', 'travel'], 'core_flow' => 'discover -> trust -> lead/order/contact'],
        'rule' => 'Never merge extension marketplace install UX with public Mall discovery/lead UX.',
    ],
    'next_public_runtime' => [
        'scaffold_path' => 'apps/public-web',
        'package_manager' => 'npm unless monorepo tooling changes',
        'required_stack' => ['Next.js', 'React', 'TypeScript', 'Tailwind', 'ESLint', 'RTL-aware component primitives'],
        'minimum_structure' => ['app/[locale]', 'components/ui', 'components/sections', 'lib/api', 'lib/theme-manifest', 'styles/tokens.css', 'tests/smoke'],
        'do_not_start_before' => ['V9 route registry exists', 'OpenAPI contract requirements are documented', 'Blade fallback boundary is documented'],
    ],
    'openapi_requirements' => [
        'public_web' => ['app/site public content', 'theme profile', 'menu/navigation', 'pricing/plans', 'Mall listings', 'developer marketplace catalog'],
        'mobile' => ['manifest', 'config', 'theme profile', 'auth', 'device registration'],
        'desktop' => ['registration', 'pull sync', 'push dry-run', 'file queue'],
        'developer' => ['package manifest validation', 'submission status', 'permissions', 'reviews', 'signing status'],
        'contract_rules' => ['version every external response', 'document auth and scopes', 'document visibility/moderation statuses', 'avoid leaking internal IDs where public slugs exist'],
    ],
];
