<?php

return [
    'version' => 'V10',
    'name' => 'KABEERI Internal Admin System Check and Core Admin UX',
    'rules' => [
        'runtime' => 'Filament is the internal admin runtime. Public marketing remains outside V10.',
        'context_first' => 'Every admin surface must show current context, what needs action, allowed actions, blocked actions, and next safe step.',
        'permission_aware' => 'Navigation visibility is UX only. Backend policies and permission checks remain mandatory.',
        'progressive_disclosure' => 'Advanced modules should appear through spaces and next actions, not as one overwhelming menu.',
        'no_destructive_shortcuts' => 'Dangerous admin actions require confirmation, auditability, and policy checks before implementation.',
    ],
    'pages' => [
        'system_check' => [
            'label' => 'System Check',
            'route' => 'filament.admin.pages.system-check',
            'uri' => '/admin/system-check',
            'task_ids' => ['T02'],
            'purpose' => 'Give the platform owner a quick truth snapshot before demos, releases, or deployment.',
        ],
        'task_tracker' => [
            'label' => 'Task Tracker',
            'route' => 'filament.admin.pages.task-tracker-status',
            'uri' => '/admin/task-tracker-status',
            'task_ids' => ['T03'],
            'purpose' => 'Show implementation truth across V1-V14, Freemium, and extension update tracks.',
        ],
        'database_status' => [
            'label' => 'Database Status',
            'route' => 'filament.admin.pages.database-status',
            'uri' => '/admin/database-status',
            'task_ids' => ['T04'],
            'purpose' => 'Expose migration and table readiness without asking the admin to inspect code.',
        ],
        'module_health' => [
            'label' => 'Module Health',
            'route' => 'filament.admin.pages.module-health',
            'uri' => '/admin/module-health',
            'task_ids' => ['T05'],
            'purpose' => 'Group the platform by operational domains and show health, records, and next action.',
        ],
        'release_readiness' => [
            'label' => 'Release Readiness',
            'route' => 'filament.admin.pages.release-readiness',
            'uri' => '/admin/release-readiness',
            'task_ids' => ['T06', 'T16'],
            'purpose' => 'Make Go/No-Go visible with tests, docs, task tracker, build, and UX gates.',
        ],
        'admin_workspaces' => [
            'label' => 'Admin Workspaces',
            'route' => 'filament.admin.pages.admin-workspaces',
            'uri' => '/admin/admin-workspaces',
            'task_ids' => ['T07', 'T09', 'T10', 'T11', 'T12', 'T17', 'T18', 'T19', 'T20', 'T21', 'T22', 'T23', 'T24', 'T25', 'T26', 'T27'],
            'purpose' => 'Show role-specific landing paths and context switching model for every admin space.',
        ],
    ],
    'module_groups' => [
        'platform' => [
            'label' => 'Platform Admin',
            'tables' => ['users', 'organizations', 'sites', 'feature_flags', 'activity_logs'],
            'routes' => ['filament.admin.pages.system-check', 'filament.admin.pages.task-tracker-status', 'filament.admin.pages.release-readiness'],
            'next_action' => 'Review task truth, feature flags, and release gates before broad changes.',
        ],
        'content' => [
            'label' => 'Content and Apps',
            'tables' => ['sites', 'content_types', 'content_entries', 'menus', 'redirects', 'forms', 'media_assets'],
            'routes' => ['filament.admin.resources.sites.index', 'filament.admin.resources.content-entries.index', 'filament.admin.resources.menus.index'],
            'next_action' => 'Choose the active Kabeeri App, then manage content, SEO, menus, and media.',
        ],
        'company_rabet' => [
            'label' => 'Company / Rabet OS',
            'tables' => ['companies', 'contacts', 'leads', 'service_requests'],
            'routes' => ['filament.admin.resources.companies.index', 'filament.admin.resources.contacts.index'],
            'next_action' => 'Confirm legal company context before verification, CRM, or public business profile work.',
        ],
        'commerce' => [
            'label' => 'Commerce Admin',
            'tables' => ['products', 'orders', 'coupons', 'payments', 'invoices'],
            'routes' => ['filament.admin.resources.products.index', 'filament.admin.resources.orders.index'],
            'next_action' => 'Review products, orders, payment placeholders, and billing handoff together.',
        ],
        'erp' => [
            'label' => 'ERP Admin',
            'tables' => ['inventory_items', 'warehouses', 'suppliers', 'purchase_orders', 'goods_receipts', 'journal_entries'],
            'routes' => ['filament.admin.resources.inventory-items.index', 'filament.admin.resources.purchase-orders.index'],
            'next_action' => 'Scope ERP work to company context and keep posting/finance actions permission-gated.',
        ],
        'mall' => [
            'label' => 'Kabeeri Mall Console',
            'tables' => ['mall_sync_sources', 'mall_mirror_businesses', 'mall_mirror_products', 'mall_mirror_services', 'mall_mirror_courses', 'mall_mirror_talent', 'travel_tourism_mall_listings'],
            'routes' => ['mall.index'],
            'next_action' => 'Separate Mall discovery, moderation, and public trust from extension Marketplace installs.',
        ],
        'developer' => [
            'label' => 'Developer Console',
            'tables' => ['packages', 'plugin_bundles', 'developer_marketplace_listings', 'marketplace_catalog_items', 'integration_connectors'],
            'routes' => ['filament.admin.resources.developer-marketplace-listings.index', 'filament.admin.resources.marketplace-catalog-items.index'],
            'next_action' => 'Show package status, permissions, review, signing, support, and compatibility before install UX.',
        ],
        'billing' => [
            'label' => 'Billing Console',
            'tables' => ['plans', 'plan_entitlements', 'usage_records', 'entitlement_overrides', 'billing_usage_records'],
            'routes' => ['filament.admin.resources.plans.index'],
            'next_action' => 'Show current plan, entitlements, limits, and upgrade/blocked-action reasons clearly.',
        ],
        'security' => [
            'label' => 'Security and Compliance',
            'tables' => ['activity_logs', 'approval_requests', 'grc_risks', 'feature_flags'],
            'routes' => ['filament.admin.resources.activity-logs.index', 'filament.admin.resources.approval-requests.index'],
            'next_action' => 'Review audit trails, approvals, blocked actions, and risk queues before sensitive changes.',
        ],
        'mobile_desktop' => [
            'label' => 'Mobile and Desktop',
            'tables' => ['mobile_app_configs', 'mobile_devices', 'desktop_clients', 'desktop_sync_sessions'],
            'routes' => ['mobile.manifest', 'desktop.register'],
            'next_action' => 'Keep shell UX tied to manifest/config/sync contracts, not Laravel internals.',
        ],
    ],
    'workspace_homes' => [
        'personal' => ['label' => 'Personal Space', 'primary_route' => 'filament.admin.pages.admin-workspaces', 'context' => 'Current user', 'empty_state' => 'No personal queue yet. Start from notifications, approvals, or assigned work when enabled.'],
        'organization' => ['label' => 'Organization Workspace', 'primary_route' => 'filament.admin.resources.organizations.index', 'context' => 'Organization', 'empty_state' => 'Create or select an organization before team, billing, or app setup.'],
        'site' => ['label' => 'Kabeeri App / Site Admin', 'primary_route' => 'filament.admin.resources.sites.index', 'context' => 'Kabeeri App / Site', 'empty_state' => 'Create or select a Kabeeri App before content, theme, menus, and SEO work.'],
        'company_rabet' => ['label' => 'Company Admin / Rabet OS', 'primary_route' => 'filament.admin.resources.companies.index', 'context' => 'Company', 'empty_state' => 'Create or select a company before Rabet verification, CRM, and business profile work.'],
        'commerce' => ['label' => 'Commerce Admin', 'primary_route' => 'filament.admin.resources.products.index', 'context' => 'Site or company commerce scope', 'empty_state' => 'Add products before orders, coupons, and payment review.'],
        'erp' => ['label' => 'ERP Admin', 'primary_route' => 'filament.admin.resources.inventory-items.index', 'context' => 'Company', 'empty_state' => 'Start with inventory and suppliers before purchasing, receipts, and finance posting.'],
        'mall' => ['label' => 'Kabeeri Mall Console', 'primary_route' => 'filament.admin.pages.module-health', 'context' => 'Public listing network', 'empty_state' => 'Publish only consented and moderated listings into Mall discovery.'],
        'talent' => ['label' => 'Talent Console', 'primary_route' => 'filament.admin.resources.employee-profiles.index', 'context' => 'Professional profile', 'empty_state' => 'Talent profiles, badges, work network, and academy flows are staged for V13.'],
        'teams' => ['label' => 'Kabeeri Teams', 'primary_route' => 'filament.admin.resources.approval-requests.index', 'context' => 'Team/workflow', 'empty_state' => 'Use approvals and workflows as the first operational team queue.'],
        'developer' => ['label' => 'Developer Console', 'primary_route' => 'filament.admin.resources.developer-marketplace-listings.index', 'context' => 'Publisher account', 'empty_state' => 'No package submission selected. Start with manifest, permissions, review, signing, and support status.'],
        'billing' => ['label' => 'Billing Console', 'primary_route' => 'filament.admin.resources.plans.index', 'context' => 'Organization or company billing', 'empty_state' => 'Seed plans and entitlements before showing usage or upgrade prompts.'],
        'platform' => ['label' => 'Platform Admin', 'primary_route' => 'filament.admin.pages.system-check', 'context' => 'Global platform', 'empty_state' => 'Use system check, task tracker, database status, and release readiness before deployment.'],
    ],
    'quick_actions' => [
        ['label' => 'Open System Check', 'route' => 'filament.admin.pages.system-check', 'intent' => 'safe_review'],
        ['label' => 'Review Task Tracker', 'route' => 'filament.admin.pages.task-tracker-status', 'intent' => 'safe_review'],
        ['label' => 'Inspect Database Status', 'route' => 'filament.admin.pages.database-status', 'intent' => 'safe_review'],
        ['label' => 'Review Release Gate', 'route' => 'filament.admin.pages.release-readiness', 'intent' => 'safe_review'],
        ['label' => 'Manage Plans', 'route' => 'filament.admin.resources.plans.index', 'intent' => 'permission_required', 'permission' => 'billing.manage'],
        ['label' => 'Review Approvals', 'route' => 'filament.admin.resources.approval-requests.index', 'intent' => 'permission_required', 'permission' => 'approval.manage'],
    ],
    'permission_aware_navigation' => [
        'principle' => 'Hidden links are not security. Policies, permissions, confirmations, and audit logs must enforce sensitive actions.',
        'blocked_actions' => [
            ['action' => 'Manage billing or upgrade plan', 'permission' => 'billing.manage', 'reason' => 'Billing changes affect subscription, limits, and invoices.'],
            ['action' => 'Approve company verification', 'permission' => 'company.verification.approve', 'reason' => 'Verification changes public trust badges and Mall reputation.'],
            ['action' => 'Post journal entry', 'permission' => 'finance.journal.post', 'reason' => 'Financial posting must be auditable and reversible only through governed flows.'],
            ['action' => 'Assign user role', 'permission' => 'users.role.assign', 'reason' => 'Role assignment changes data access across workspaces.'],
            ['action' => 'Install plugin/package', 'permission' => 'plugin.install', 'reason' => 'Packages may request data permissions and migrations.'],
            ['action' => 'Apply sensitive AI change', 'permission' => 'ai.apply_sensitive_change', 'reason' => 'AI suggestions that affect finance, payroll, security, or legal data require explicit approval.'],
        ],
    ],
    'release_gates' => [
        ['key' => 'v9_foundation_ready', 'label' => 'V9 UI foundation ready', 'source' => 'App\\Support\\Ui\\V9UiFoundation::isReleaseCandidateReady'],
        ['key' => 'v10_pages_registered', 'label' => 'V10 Filament pages registered', 'source' => 'V10 page route registry'],
        ['key' => 'task_tracker_synced', 'label' => 'V10 task tracker synced', 'source' => '24_kabeeri_task_tracking/tasks/v10.tasks.json'],
        ['key' => 'docs_ready', 'label' => 'V10 docs ready', 'source' => 'docs/kabeeri/ui/V10_ADMIN_UX.md'],
        ['key' => 'smoke_tests_ready', 'label' => 'V10 admin smoke tests ready', 'source' => 'tests/Feature/V10AdminExperienceTest.php'],
    ],
];
