<?php

return [
    'version' => 'V11',
    'name' => 'KABEERI Public Marketing, Audience, and Onboarding UX',
    'rules' => [
        'runtime' => 'Laravel Blade is a public bridge for V11. The long-term public runtime remains Next.js + React + TypeScript + Tailwind.',
        'narrative' => 'Do not sell the whole platform at once. Progress from website/CMS to commerce, trust, operations, Mall visibility, and full company OS.',
        'audience_first' => 'Every public page must identify who it is for, what pain it solves, and the next onboarding step.',
        'rtl_mobile' => 'Arabic RTL and mobile responsiveness are mandatory for every V11 bridge page.',
        'conversion_safety' => 'Inquiry flow creates CRM leads with explicit metadata and no sensitive automation.',
    ],
    'pages' => [
        'landing' => ['label' => 'Public Landing', 'route' => 'public.landing', 'uri' => '/public', 'task_ids' => ['T02', 'T20'], 'intent' => 'Explain Kabeeri progressively.'],
        'audiences' => ['label' => 'Audience Selector', 'route' => 'public.audiences', 'uri' => '/for', 'task_ids' => ['T03'], 'intent' => 'Help visitors choose the right path.'],
        'business' => ['label' => 'Business Owner Path', 'route' => 'public.business', 'uri' => '/for/business-owners', 'task_ids' => ['T04'], 'intent' => 'Website, commerce, CRM, operations, and Mall growth.'],
        'enterprise' => ['label' => 'Enterprise Buyer Path', 'route' => 'public.enterprise', 'uri' => '/for/enterprise', 'task_ids' => ['T05'], 'intent' => 'Governance, security, integrations, BI, and GRC.'],
        'developers' => ['label' => 'Developer and Creator Path', 'route' => 'public.developers', 'uri' => '/for/developers-creators', 'task_ids' => ['T22'], 'intent' => 'Themes, plugins, packages, review, signing, and revenue.'],
        'partners' => ['label' => 'Marketer and Partner Path', 'route' => 'public.partners', 'uri' => '/for/marketers-partners', 'task_ids' => ['T24'], 'intent' => 'Referral, campaigns, lead handoff, and partner revenue.'],
        'wordpress' => ['label' => 'WordPress Alternative', 'route' => 'public.wordpress', 'uri' => '/wordpress-alternative', 'task_ids' => ['T21'], 'intent' => 'Position Kabeeri as simpler website/CMS and commerce growth path.'],
        'service_business' => ['label' => 'Service Business Use Case', 'route' => 'public.service-business', 'uri' => '/use-cases/service-business', 'task_ids' => ['T23'], 'intent' => 'Show booking, services, CRM, quotations, invoices, and Mall discovery.'],
        'templates' => ['label' => 'Use Cases and Templates', 'route' => 'public.templates', 'uri' => '/templates', 'task_ids' => ['T10'], 'intent' => 'Industry templates without overwhelming the visitor.'],
        'onboarding' => ['label' => 'Onboarding Overview', 'route' => 'public.onboarding', 'uri' => '/onboarding', 'task_ids' => ['T06'], 'intent' => 'Explain onboarding from audience to workspace to first launch.'],
        'workspace_setup' => ['label' => 'Workspace Setup Wizard', 'route' => 'public.workspace-setup', 'uri' => '/onboarding/workspace-setup', 'task_ids' => ['T07'], 'intent' => 'Preview setup wizard structure and progressive disclosure.'],
        'pricing' => ['label' => 'Pricing and Plans', 'route' => 'public.pricing', 'uri' => '/pricing', 'task_ids' => ['T08', 'T09', 'T26'], 'intent' => 'Explain subscriptions, modules, verification, Mall visibility, AI credits, and revenue share.'],
        'trust' => ['label' => 'FAQ and Trust', 'route' => 'public.trust', 'uri' => '/trust', 'task_ids' => ['T11'], 'intent' => 'Answer risk, ownership, privacy, marketplace, Mall, and migration questions.'],
        'contact' => ['label' => 'Contact Sales', 'route' => 'public.contact', 'uri' => '/contact-sales', 'task_ids' => ['T12', 'T25'], 'intent' => 'Capture qualified inquiries into CRM leads.'],
    ],
    'story_layers' => [
        ['step' => '01', 'title' => 'Website that is clearer than WordPress chaos', 'text' => 'Start with a Kabeeri App: pages, content, SEO, media, forms, and menus without plugin sprawl.'],
        ['step' => '02', 'title' => 'Commerce without WooCommerce weight', 'text' => 'Add products, services, orders, coupons, payment placeholders, and quoting when the business is ready.'],
        ['step' => '03', 'title' => 'Trusted company identity through Rabet', 'text' => 'Connect business profile, verification, contacts, and public trust signals.'],
        ['step' => '04', 'title' => 'Operations when the team grows', 'text' => 'Move into CRM, service requests, quotations, invoices, inventory, purchasing, workflows, reports, and approvals gradually.'],
        ['step' => '05', 'title' => 'Visibility through Kabeeri Mall', 'text' => 'Publish moderated and consented businesses, products, services, courses, talent, and travel listings.'],
        ['step' => '06', 'title' => 'Platform economy', 'text' => 'Developers, agencies, creators, marketers, and partners can build, sell, refer, and support inside the ecosystem.'],
    ],
    'audiences' => [
        'business' => ['label' => 'Business Owner', 'route' => 'public.business', 'headline' => 'Launch a serious business presence, then grow into operations.', 'pain' => 'You need a website, content, leads, commerce, invoices, and visibility without managing disconnected plugins.', 'outcome' => 'Start with a Kabeeri App, add commerce and CRM, then graduate to Company OS and Mall visibility.'],
        'enterprise' => ['label' => 'Enterprise Buyer', 'route' => 'public.enterprise', 'headline' => 'Govern teams, data, integrations, and risk from one controlled platform.', 'pain' => 'You need permissions, audit trails, integration control, BI/GRC readiness, and deployment discipline.', 'outcome' => 'Use Laravel/Filament admin, policies, activity logs, release gates, APIs, mobile, desktop, BI, and GRC tracks.'],
        'developers' => ['label' => 'Developer / Creator', 'route' => 'public.developers', 'headline' => 'Build themes, plugins, connectors, and business kits for the Kabeeri economy.', 'pain' => 'You need a marketplace path with manifests, permissions, compatibility, signing, support, and revenue.', 'outcome' => 'Create packages, pass review, publish into Marketplace, and sell or support customers.'],
        'partners' => ['label' => 'Marketer / Partner', 'route' => 'public.partners', 'headline' => 'Turn campaigns, referrals, and delivery partners into measurable growth.', 'pain' => 'You need lead handoff, campaign assets, referral visibility, partner storefronts, and revenue rules.', 'outcome' => 'Use partner paths, referral tracking, CRM handoff, Academy/work network, and later revenue dashboards.'],
        'mall' => ['label' => 'Mall Visitor', 'route' => 'mall.index', 'headline' => 'Discover trusted businesses, products, services, courses, talent, and travel.', 'pain' => 'You need public discovery with trust, moderation, verification, and clear listing types.', 'outcome' => 'Browse Kabeeri Mall and contact verified or published listings.'],
    ],
    'journeys' => [
        'business' => ['Pick your business path', 'Create Kabeeri App', 'Add content and services', 'Capture leads', 'Add commerce and invoices', 'Publish to Mall when trusted'],
        'enterprise' => ['Map governance scope', 'Define organizations and companies', 'Review permissions and audit', 'Connect APIs and integrations', 'Plan BI/GRC', 'Run release gates'],
        'developers' => ['Create publisher profile', 'Build manifest', 'Run local tests', 'Submit for review', 'Pass permission/security checks', 'Sign and publish'],
        'partners' => ['Choose partner path', 'Create campaign or storefront', 'Capture/referral lead', 'Handoff to CRM', 'Measure progress', 'Prepare revenue share'],
    ],
    'onboarding_steps' => [
        ['n' => '01', 'title' => 'Audience and intent', 'text' => 'Choose business owner, enterprise, developer/creator, marketer/partner, agency, or Mall visitor.'],
        ['n' => '02', 'title' => 'Workspace', 'text' => 'Create Organization, Company if needed, and first Kabeeri App.'],
        ['n' => '03', 'title' => 'App recipe', 'text' => 'Pick website, service business, store, landing, portal, or content hub.'],
        ['n' => '04', 'title' => 'Theme and modules', 'text' => 'Select bridge theme now, later Next.js theme runtime, and enable only needed modules.'],
        ['n' => '05', 'title' => 'Team and permissions', 'text' => 'Invite users, set roles, and explain blocked actions clearly.'],
        ['n' => '06', 'title' => 'Launch and grow', 'text' => 'Publish content, capture leads, add commerce/operations, and graduate to Mall/Marketplace paths.'],
    ],
    'wizard' => [
        'fields' => ['audience', 'business_type', 'organization_name', 'company_needed', 'first_app_type', 'locale', 'currency', 'modules', 'team_size', 'plan_intent'],
        'progressive_rules' => ['Ask only what the selected audience needs now.', 'Hide ERP until company context exists.', 'Hide Marketplace install until developer/owner context exists.', 'Hide Mall publishing until trust/moderation prerequisites are explained.'],
    ],
    'pricing_layers' => [
        ['label' => 'Subscription', 'text' => 'Free, Starter, Business, Agency, Enterprise plans and entitlements.'],
        ['label' => 'Modules', 'text' => 'Commerce, CRM, ERP, Marketplace, BI/GRC, mobile/desktop capabilities.'],
        ['label' => 'Verification', 'text' => 'Rabet/company verification and public trust upgrades.'],
        ['label' => 'Mall visibility', 'text' => 'Featured listings, sponsored placement, lead generation, and discovery upgrades.'],
        ['label' => 'AI and automation', 'text' => 'AI credits, sensitive-change approval, and automation limits.'],
        ['label' => 'Marketplace revenue', 'text' => 'Developer, creator, agency, and partner revenue share rules.'],
    ],
    'plans' => [
        ['code' => 'free', 'name' => 'Free / Community', 'price' => 'Free', 'best_for' => 'Early exploration and one simple app.', 'highlight' => 'Start without risk.'],
        ['code' => 'starter', 'name' => 'Starter / Pro', 'price' => '$19/mo', 'best_for' => 'Solo business with public website and lead capture.', 'highlight' => 'A focused launch path.'],
        ['code' => 'business', 'name' => 'Business', 'price' => '$49/mo', 'best_for' => 'Growing company with commerce, CRM, and operations.', 'highlight' => 'Best growth baseline.'],
        ['code' => 'agency', 'name' => 'Agency', 'price' => '$99/mo', 'best_for' => 'Agencies managing multiple clients and reusable kits.', 'highlight' => 'Scale service delivery.'],
        ['code' => 'enterprise', 'name' => 'Enterprise', 'price' => 'Custom', 'best_for' => 'Governance, security, integrations, BI/GRC, and contracts.', 'highlight' => 'Controlled platform adoption.'],
    ],
    'templates' => [
        ['title' => 'Service Business', 'route' => 'public.service-business', 'includes' => ['services', 'booking inquiry', 'CRM', 'quotations', 'invoices', 'Mall listing']],
        ['title' => 'Professional Company', 'route' => 'public.business', 'includes' => ['website', 'Rabet profile', 'forms', 'team', 'reports']],
        ['title' => 'Commerce Starter', 'route' => 'public.business', 'includes' => ['products', 'orders', 'coupons', 'payments', 'Mall products']],
        ['title' => 'Agency Client Kit', 'route' => 'public.developers', 'includes' => ['themes', 'templates', 'client workspaces', 'partner flow']],
        ['title' => 'Enterprise Governance', 'route' => 'public.enterprise', 'includes' => ['permissions', 'audit', 'integrations', 'BI', 'GRC']],
    ],
    'faq' => [
        ['q' => 'Is Kabeeri only a website builder?', 'a' => 'No. It starts as a clearer website/CMS path, then grows into commerce, CRM, operations, Mall, Marketplace, mobile, desktop, and enterprise governance.'],
        ['q' => 'Why not just WordPress?', 'a' => 'WordPress can be powerful, but many businesses end in plugin sprawl. Kabeeri aims for controlled modules, admin governance, and business operations in one product path.'],
        ['q' => 'Are themes Blade or Next.js?', 'a' => 'Current Laravel pages are a bridge. Long-term public commercial themes target Next.js + React + TypeScript + Tailwind through API contracts.'],
        ['q' => 'What is the difference between Marketplace and Mall?', 'a' => 'Marketplace is internal extensions: themes, plugins, connectors, AI skills. Mall is public discovery: businesses, products, services, talent, courses, and travel.'],
        ['q' => 'Can developers sell on the platform?', 'a' => 'Yes, the planned developer economy includes package manifests, review, permissions, signing, publishing, support obligations, and revenue share.'],
        ['q' => 'How does trust work?', 'a' => 'Trust is built through Rabet/company profile, moderation, publication consent, auditability, and explicit review paths.'],
    ],
    'contact' => [
        'organization_slug' => 'kabeeri-public-inquiries',
        'organization_name' => 'KABEERI Public Inquiries',
        'owner_email' => 'public-inquiries@kabeeri.local',
    ],
    'next_runtime' => [
        'decision' => 'Do not scaffold Next.js before V11 contracts and migration path are documented. V11 documents the setup plan and keeps Blade as bridge.',
        'scaffold_path' => 'apps/public-web',
        'contract_needs' => ['plans/pricing', 'public app content', 'audience journeys', 'lead capture', 'Mall listings', 'theme profile', 'navigation/menu'],
        'migration_steps' => ['Keep Blade bridge pages', 'Expose/confirm API contracts', 'Scaffold apps/public-web', 'Move marketing/onboarding first', 'Move Marketplace and Mall later', 'Run V14 parity and accessibility QA'],
    ],
    'release_gates' => [
        ['key' => 'v9_ready', 'label' => 'V9 foundation ready'],
        ['key' => 'v10_ready', 'label' => 'V10 admin command ready'],
        ['key' => 'routes_ready', 'label' => 'V11 public routes registered'],
        ['key' => 'inquiry_flow_ready', 'label' => 'Contact inquiry flow creates CRM leads'],
        ['key' => 'docs_ready', 'label' => 'V11 docs ready'],
        ['key' => 'smoke_tests_ready', 'label' => 'V11 smoke tests ready'],
    ],
];
